services:
    nginx:
        image: nginx:1.29
        ports:
            - "${WEB_PORT:-8080}:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            # Media and static files
            - static_files:/static
            - ./data:/data
        depends_on:
            # - ghost
            - web
    web:
        build: .
        # user: "${DOCKER_WEB_USER:-bca}"
        restart: always
        env_file: [.env]
        command: ["./entrypoint.sh"]
        ports:
            - 8000:8000
        volumes:
            - ./entrypoint.sh:/usr/src/app/entrypoint.sh
            # Update Django files in real-time
            - .:/usr/src/app
            # Media and static files
            - static_files:/usr/src/app/static
            - ./data:/usr/src/app/data
        depends_on:
            db:
                condition: service_healthy
volumes:
    static_files:
    # ghost_data:
